#!/usr/bin/env uv run --script
"""
Generate the slim IML prelude from imandra-ai/imandrax-api.

The upstream prelude is `imandrax-extract`'s output for src/prelude/prelude.iml.
We keep it as close to verbatim as possible so it stays easy to regenerate when
ImandraX's prelude changes; every edit is listed in TRANSFORMS below and is
mechanical.

Usage:
    uv run --script gen_prelude.py [--check]

    --check  fail if the checked-in iml_prelude.ml differs from a fresh
             generation (catches both a stale checked-in copy and upstream
             having moved)
"""

import argparse
import pathlib
import re
import sys
import urllib.error
import urllib.request

SOURCE_URL = (
    'https://raw.githubusercontent.com/imandra-ai/imandrax-api/'
    'main/src/prelude/imandrax_api_prelude.ml'
)

HEADER = """(* GENERATED by gen_prelude.py from imandrax-api -- do not edit by hand.

   The slim IML prelude: the admitted-IML surface only, with arithmetic over
   Zq's canonical bignums instead of zarith, and with no dependency on
   imandrax-api.
   Regenerate with:  python3 gen_prelude.py                                  *)

module Z = Zq.Z
module Q = Zq.Q

"""

# Each transform is (description, function). Keep them mechanical and few.
TRANSFORMS = []


def transform(desc):
    def wrap(fn):
        TRANSFORMS.append((desc, fn))
        return fn

    return wrap


@transform(
    'strip [@@deriving (to_iml, of_mir)] -- the sole source of the '
    'imandrax-api / MIR / Yojson / Uuidm / Unix dependency chain'
)
def strip_deriving(src):
    return re.sub(r'\[@@deriving\s*\((?:to_iml|of_mir|\s|,)*\)\]', '', src)


@transform(r"rewrite ImandraX's escaped identifier \#mod to OCaml's (mod)")
def fix_mod(src):
    return src.replace(r'\#mod', '(mod)')


@transform(
    "bind int's ordering/min/max to Zq instead of polymorphic Stdlib "
    'compare, which on a Zq.Z.t is structural -- sign, then limb count, '
    'then limbs least-significant first -- and so is not numeric order. '
    "Equality is deliberately left polymorphic: Zq's canonicality "
    'contract makes structural equality numerically correct.'
)
def fix_int_ordering(src):
    subs = [
        (
            r'let \(>=\) : int -> int -> bool = Stdlib\.\(>=\)',
            'let (>=) : int -> int -> bool = Z.geq',
        ),
        (
            r'let \(<\) : int -> int -> bool = \(<\)',
            'let (<) : int -> int -> bool = Z.lt',
        ),
        (
            r'let \(<=\) : int -> int -> bool = \(<=\)',
            'let (<=) : int -> int -> bool = Z.leq',
        ),
        (
            r'let \(>\) : int -> int -> bool = \(>\)',
            'let (>) : int -> int -> bool = Z.gt',
        ),
        (r'let min : int -> int -> int = min', 'let min : int -> int -> int = Z.min'),
        (r'let max : int -> int -> int = max', 'let max : int -> int -> int = Z.max'),
    ]
    for pat, rep in subs:
        src, n = re.subn(pat, rep, src)
        if n != 1:
            sys.exit(
                f'gen_prelude: expected exactly 1 match for {pat!r}, got {n}. '
                'Upstream prelude changed; re-check the transform.'
            )
    return src


def prelude_source():
    """Fetch the upstream prelude from main and return it as text."""
    try:
        with urllib.request.urlopen(SOURCE_URL, timeout=30) as resp:
            return resp.read().decode()
    except urllib.error.URLError as e:
        sys.exit(f'gen_prelude: cannot fetch {SOURCE_URL}: {e}')


def generate():
    src = prelude_source()
    for _desc, fn in TRANSFORMS:
        src = fn(src)
    return HEADER + src


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    target = pathlib.Path(__file__).parent / 'iml_prelude.ml'
    fresh = generate()

    if args.check:
        if not target.exists() or target.read_text() != fresh:
            sys.exit(f'{target.name} is stale; run: python3 gen_prelude.py')
        print(f'{target.name} is up to date')
        return

    target.write_text(fresh)
    print(f'wrote {target} ({len(fresh.splitlines())} lines)')
    for desc, _fn in TRANSFORMS:
        print(f'  - {desc}')


if __name__ == '__main__':
    main()
