"""
Generate JS test fixtures for the region-decomp widget from real API output.

Two files are written per example under `test/fixtures/region_decomp/`:

- `<name>.enriched_decompose_res.jsonc` -- the raw `EnrichedDecomposeRes` dump,
  kept as an API-response cache. The API call is skipped when it already exists;
  pass `--refresh` to force re-calling the API (needs `IMANDRAX_API_KEY`).
- `<name>.widget_data.jsonc` -- the exact `RegionDecompWidget` input, i.e. the
  list `region_decomp_widget` feeds to the frontend (`_region_group_node` per
  group, carrying `region_stat`). This is what the JS tests load, so they
  exercise the real production shape. Always regenerated from the raw cache, so
  adapting the widget shape only needs a re-run -- no API call.

Flag:
    --refresh: force re-calling the API and regenerating the raw cache
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

import imandrax_api
from imandrax_api_models.client import ImandraXClient
from imandrax_api_models.proto_models import DecomposeRes
from imandrax_api_models.region_decomp import EnrichedDecomposeRes

PKG_ROOT = Path(__file__).resolve().parents[1]
API_MODELS_ROOT = PKG_ROOT.parents[1] / 'imandrax-api-models'
OUT_DIR = PKG_ROOT / 'test/fixtures/region_decomp'

CLASSIFY_IML = """\
let classify (x : int) (y : int) : int =
if x > 0 then
    if y > 0 then
    if x > y then 1
    else 2
    else
    if y < -10 then 3
    else 4
else
    if y > 0 then 5
    else 6"""

EXAMPLES = [
    ('classify', 'classify', CLASSIFY_IML),
    (
        'six_swiss',
        'match_price',
        (API_MODELS_ROOT / 'tests/data/six_swiss.iml').read_text(),
    ),
]


HEADER = '// Auto-generated by {path}; DO NOT EDIT\n'


def call(decompose_name: str, iml: str) -> EnrichedDecomposeRes:
    """Call the API and return the enriched DecomposeRes."""
    c = ImandraXClient(
        url=imandrax_api.url_dev, auth_token=os.environ['IMANDRAX_API_KEY']
    )
    c.eval_src(iml)
    decomp_res = c.decompose(name=decompose_name, string_results=True, prune=True)
    return EnrichedDecomposeRes.from_decomp_res(decomp_res)


def load_enriched(raw_path: Path) -> EnrichedDecomposeRes:
    """
    Rebuild an `EnrichedDecomposeRes` from a cached raw dump.

    The dump's own `region_groups` are ignored (validated as a plain
    `DecomposeRes`, which drops the extra field), then re-grouped from the
    artifact so the `Region`s carry their live `mir_region` -- exactly as a
    fresh API call would.
    """
    raw = re.sub(r'^\s*//.*$', '', raw_path.read_text(), flags=re.M)
    return EnrichedDecomposeRes.from_decomp_res(DecomposeRes.model_validate_json(raw))


def main() -> None:
    refresh = '--refresh' in sys.argv[1:]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, decompose_name, iml in EXAMPLES:
        raw_path = OUT_DIR / f'{name}.enriched_decompose_res.jsonc'
        data_path = OUT_DIR / f'{name}.widget_data.jsonc'

        if refresh or not raw_path.exists():
            enriched = call(decompose_name, iml)
            raw_path.write_text(
                HEADER.format(path=__file__) + enriched.model_dump_json(indent=2) + '\n'
            )
            print(f'[{name}] wrote {raw_path.relative_to(PKG_ROOT)}')
        else:
            enriched = load_enriched(raw_path)
            print(f'[{name}] using cached {raw_path.relative_to(PKG_ROOT)}')

        # The exact `RegionDecompWidget` input: `region_group_views()` serialised,
        # matching what `region_decomp_widget` feeds the frontend.
        data = [v.model_dump(mode='json') for v in enriched.region_group_views()]
        data_path.write_text(
            HEADER.format(path=__file__) + json.dumps(data, indent=2) + '\n'
        )
        print(f'[{name}] wrote {data_path.relative_to(PKG_ROOT)}')


if __name__ == '__main__':
    main()
