"""
Generate JS test fixtures for the region-decomp widget from real API output.

The API call is skipped when the raw file already exists. Pass `--refresh` to
force re-calling the API (needs `IMANDRAX_API_KEY`).

Run from anywhere:

    uv run python widget-js/scripts/gen_fixtures.py [--refresh]
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import imandrax_api
from imandrax_api_models.client import ImandraXClient
from imandrax_api_models.region_decomp import EnrichedDecomposeRes

PKG_ROOT = Path(__file__).resolve().parents[1]
API_MODELS_ROOT = PKG_ROOT.parents[1] / 'imandrax-api-models'
OUT_DIR = PKG_ROOT / 'test/fixtures/region_decomp'

CLASSIFY_IML = """\
let classify (x : int) (y : int) : int =
if x > 0 then
    if y > 0 then
    if x > y then 1
    else 2
    else
    if y < -10 then 3
    else 4
else
    if y > 0 then 5
    else 6"""

EXAMPLES = [
    ('classify', 'classify', CLASSIFY_IML),
    (
        'six_swiss',
        'match_price',
        (API_MODELS_ROOT / 'tests/data/six_swiss.iml').read_text(),
    ),
]


def call(decompose_name: str, iml: str) -> EnrichedDecomposeRes:
    """Call the API and return the raw DecomposeRes."""
    c = ImandraXClient(
        url=imandrax_api.url_dev, auth_token=os.environ['IMANDRAX_API_KEY']
    )
    c.eval_src(iml)
    decomp_res = c.decompose(name=decompose_name, string_results=True, prune=True)
    return EnrichedDecomposeRes.from_decomp_res(decomp_res)


def main() -> None:
    refresh = '--refresh' in sys.argv[1:]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, decompose_name, iml in EXAMPLES:
        out_path = OUT_DIR / f'{name}.enriched_decompose_res.jsonc'
        if refresh or not out_path.exists():
            decomp_res = call(decompose_name, iml)
            out_path.write_text(
                f'// Auto-generated by {__file__}; DO NOT EDIT\n'
                + decomp_res.model_dump_json(indent=2)
                + '\n'
            )
            print(f'[{name}] wrote {out_path.relative_to(PKG_ROOT)}')
        else:
            print(
                f'[{name}] cached exists at {out_path.relative_to(PKG_ROOT)}; skipping'
            )


if __name__ == '__main__':
    main()
