from __future__ import annotations

import re
from enum import Enum
from typing import Self

from pydantic import Field

from ..proto_utils import BaseModel
from .locs import Location


class ErrorKindParsingError(Exception):
    pass


class ErrorKind(Enum):
    # >>> Generated by imandrax-tools/scripts/imandrax_error_kind/
    APPLIED_SYMBOL_TYPE_ERR = 'AppliedSymbolTypeErr'
    CONFIG_ERROR = 'ConfigError'
    CPTR_GET_OTHER_ERR = 'CptrGetOtherErr'
    CPTR_NOT_FOUND_IN_STORAGE = 'CptrNotFoundInStorage'
    GENERIC_USER_ERROR = 'GenericUserError'
    INVALID_FUN_DEFINITION = 'InvalidFunDefinition'
    INVALID_QIDENT = 'InvalidQident'
    INVALID_TYPE_ALIAS = 'InvalidTypeAlias'
    INVALID_TYPE_DEFINITION = 'InvalidTypeDefinition'
    INVALID_CNAME = 'InvalidCname'
    LEVAL_ERROR = 'LevalError'
    LOWER_CIR_ERROR = 'LowerCirError'
    LOWER_MIR_ERROR = 'LowerMirError'
    LOWER_RIR_ERROR = 'LowerRirError'
    PARSER_NOT_REGISTERED = 'ParserNotRegistered'
    PATMATCH_ERROR = 'PatmatchError'
    SYN_TERM_CREATE_ERROR = 'SynTermCreateError'
    SYNTAX_ATTRIBUTE_ERR = 'SyntaxAttributeErr'
    SYNTAX_ERR = 'SyntaxErr'
    SYNTAX_UNSUGAR_ERR = 'SyntaxUnsugarErr'
    TACTIC_EVAL_ERR = 'TacticEvalErr'
    TERM_INVALID_SHAPE = 'TermInvalidShape'
    TERM_MODEL_FI_ERR = 'TermModelFIErr'
    THREAD_FUT_FAILURE = 'ThreadFutFailure'
    THREAD_TIMER_FAILURE = 'ThreadTimerFailure'
    TY_INFER_INTERNAL_ERROR = 'TyInferInternalError'
    TYPE_ARITY_MISMATCH = 'TypeArityMismatch'
    TYPE_CYCLE_DETECTED = 'TypeCycleDetected'
    TYPE_ERR = 'TypeErr'
    TYPE_VAR_ALREADY_BOUND = 'TypeVarAlreadyBound'
    TYPED_SYMBOL_NON_GROUND = 'TypedSymbolNonGround'
    UID_CONTENT_ADDRESSING_NAME_MISMATCH = 'UidContentAddressingNameMismatch'
    UID_CONTENT_ADDRESSING_NOT_TEMPORARY = 'UidContentAddressingNotTemporary'
    UID_NOT_CONTENT_ADDRESSED = 'UidNotContentAddressed'
    UNKNOWN_BUILTIN_SYMBOL_FOR_UID = 'UnknownBuiltinSymbolForUid'
    UNKNOWN_TYPE_DEFINITION = 'UnknownTypeDefinition'
    INTERACTIVE_PROOF_ERR = 'InteractiveProofErr'
    PROOF_DESER_ERROR = 'ProofDeserError'
    PROOF_CHECK_ERROR = 'ProofCheckError'
    INVALID_ANCHOR = 'InvalidAnchor'
    INDUCT_SCHEMA_ERROR = 'InductSchemaError'
    UNSUPPORTED = 'Unsupported'
    LOWER_FOL_ERROR = 'LowerFolError'
    VALIDATION_ERROR = 'ValidationError'
    LSP_ERROR = 'LspError'
    INTERRUPTED = 'Interrupted'
    REDIS_ERROR = 'RedisError'
    CIR_DECL_NOT_FOUND_IN_STORAGE = 'CIRDeclNotFoundInStorage'
    SERIALIZATION_ERROR = 'SerializationError'
    DESERIALIZATION_ERROR = 'DeserializationError'
    DEBUG_MODE = 'DebugMode'
    IMPORT_ERROR = 'ImportError'
    GENERIC_IO_ERROR = 'GenericIOError'
    DUNE_ERROR = 'DuneError'
    RPC_ERROR = 'RpcError'
    RPC_DESER_ERROR = 'RpcDeserError'
    RPC_NETWORK_ERROR = 'RpcNetworkError'
    RPC_TIMEOUT = 'RpcTimeout'
    AUTH_ERROR = 'AuthError'
    FILE_EXISTS = 'FileExists'
    DIRECTORY_CREATION_ERROR = 'DirectoryCreationError'
    DECOMP_ERROR = 'DecompError'
    VERSION_MISMATCH_ERROR = 'VersionMismatchError'
    OH_NO_ERROR = 'OhNoError'
    DEBOUNCED = 'Debounced'
    FILE_NOT_FOUND = 'FileNotFound'
    # <<< End of generated code
    # Manually added
    GENERIC_INTERNAL_ERROR = 'GenericInternalError'

    @classmethod
    def from_proto_kind_exn(cls, proto_kind: str) -> Self:
        kinds = re.findall(r'\{ Kind.name = "(.+)" \}', proto_kind)
        if len(kinds) != 1:
            raise ErrorKindParsingError('Unable to parse kind')
        return cls(kinds[0])

    @property
    def description(self) -> str:
        return ERROR_KIND_DESCRIPTIONS[self]


ERROR_KIND_DESCRIPTIONS: dict[ErrorKind, str] = {
    # >>> Generated by imandrax-tools/scripts/imandrax_error_kind/
    ErrorKind.APPLIED_SYMBOL_TYPE_ERR: 'AppliedSymbol could not be created because of a type mismatch',
    ErrorKind.CONFIG_ERROR: 'Error in CLI arguments or configuration',
    ErrorKind.CPTR_GET_OTHER_ERR: 'Other error in `Cptr.get`',
    ErrorKind.CPTR_NOT_FOUND_IN_STORAGE: 'Data for a `cptr` was not found in persistent storage',
    ErrorKind.GENERIC_USER_ERROR: 'user error',
    ErrorKind.INVALID_FUN_DEFINITION: 'Function definition is not valid',
    ErrorKind.INVALID_QIDENT: 'invalid qualified identifier',
    ErrorKind.INVALID_TYPE_ALIAS: 'Type alias is not well-formed',
    ErrorKind.INVALID_TYPE_DEFINITION: 'Type definition is not valid',
    ErrorKind.INVALID_CNAME: 'Not a valid Cname',
    ErrorKind.LEVAL_ERROR: 'Error in lightweight evaluation',
    ErrorKind.LOWER_CIR_ERROR: 'Error in lowering typingtree to CIR',
    ErrorKind.LOWER_MIR_ERROR: 'Error in lowering CIR to MIR',
    ErrorKind.LOWER_RIR_ERROR: 'Error in lowering MIR to RIR',
    ErrorKind.PARSER_NOT_REGISTERED: 'Parser for this syntax was not registered',
    ErrorKind.PATMATCH_ERROR: 'Error in pattern matching compilation',
    ErrorKind.SYN_TERM_CREATE_ERROR: 'Error when creating a Syn_term',
    ErrorKind.SYNTAX_ATTRIBUTE_ERR: 'error in parsing attributes',
    ErrorKind.SYNTAX_ERR: 'syntax error',
    ErrorKind.SYNTAX_UNSUGAR_ERR: 'error in unsugaring OCaml syntax',
    ErrorKind.TACTIC_EVAL_ERR: 'error when evaluating a tactic term',
    ErrorKind.TERM_INVALID_SHAPE: 'Term has an invalid shape for this operation',
    ErrorKind.TERM_MODEL_FI_ERR: 'Error during creation of a FI (function interpretation) in TermModel',
    ErrorKind.THREAD_FUT_FAILURE: 'Failure in future',
    ErrorKind.THREAD_TIMER_FAILURE: 'Failure in timer',
    ErrorKind.TY_INFER_INTERNAL_ERROR: 'internal error in type inference',
    ErrorKind.TYPE_ARITY_MISMATCH: 'number of parameters does not match expected arity',
    ErrorKind.TYPE_CYCLE_DETECTED: 'Type variable occurs inside the type is is about to be bound to',
    ErrorKind.TYPE_ERR: 'type error',
    ErrorKind.TYPE_VAR_ALREADY_BOUND: 'Type variable is already bound',
    ErrorKind.TYPED_SYMBOL_NON_GROUND: 'Type cannot be turned into a nullary type schema',
    ErrorKind.UID_CONTENT_ADDRESSING_NAME_MISMATCH: 'Uid has a different name than the Cname.t it should become',
    ErrorKind.UID_CONTENT_ADDRESSING_NOT_TEMPORARY: 'Uid was not created as a temporary to be turned into a Cname.t',
    ErrorKind.UID_NOT_CONTENT_ADDRESSED: 'Uid is not a Cname',
    ErrorKind.UNKNOWN_BUILTIN_SYMBOL_FOR_UID: 'No builtin symbol are know for this Uid',
    ErrorKind.UNKNOWN_TYPE_DEFINITION: 'Type definition could not be found',
    ErrorKind.INTERACTIVE_PROOF_ERR: 'Error in interactive proof',
    ErrorKind.PROOF_DESER_ERROR: 'Error when deserializing a proof',
    ErrorKind.PROOF_CHECK_ERROR: 'Error during proof checking',
    ErrorKind.INVALID_ANCHOR: 'Error when parsing an anchor',
    ErrorKind.INDUCT_SCHEMA_ERROR: 'Error when generating an induction schema',
    ErrorKind.UNSUPPORTED: 'Unsupported feature',
    ErrorKind.LOWER_FOL_ERROR: 'Error in lowering RIR to FOL',
    ErrorKind.VALIDATION_ERROR: 'Error while validating a definition',
    ErrorKind.LSP_ERROR: 'Error in LSP server',
    ErrorKind.INTERRUPTED: 'Computation was interrupted',
    ErrorKind.REDIS_ERROR: 'Redis error',
    ErrorKind.CIR_DECL_NOT_FOUND_IN_STORAGE: 'CIR storage error',
    ErrorKind.SERIALIZATION_ERROR: 'Error during serialization',
    ErrorKind.DESERIALIZATION_ERROR: 'Error during deserialization',
    ErrorKind.DEBUG_MODE: 'Feature disabled/inactive for debug reasons',
    ErrorKind.IMPORT_ERROR: 'Import failed',
    ErrorKind.GENERIC_IO_ERROR: 'Generic IO error',
    ErrorKind.DUNE_ERROR: 'Error related to handling of dune projects',
    ErrorKind.RPC_ERROR: 'Error in RPC',
    ErrorKind.RPC_DESER_ERROR: 'Deserialization error in RPC',
    ErrorKind.RPC_NETWORK_ERROR: 'Network error in RPC',
    ErrorKind.RPC_TIMEOUT: 'Timeout in RPC',
    ErrorKind.AUTH_ERROR: 'Authentication error',
    ErrorKind.FILE_EXISTS: 'File already exists',
    ErrorKind.DIRECTORY_CREATION_ERROR: 'Error while creating directory',
    ErrorKind.DECOMP_ERROR: 'Error during decomposition',
    ErrorKind.VERSION_MISMATCH_ERROR: 'Versions do not match',
    ErrorKind.OH_NO_ERROR: 'Oh no 😰',
    ErrorKind.DEBOUNCED: 'Task has been cancelled due to debouncing',
    ErrorKind.FILE_NOT_FOUND: 'A file could not be found',
    # <<< End of generated code
    # Manually added
    ErrorKind.GENERIC_INTERNAL_ERROR: 'Internal error',
}


class ErrorMessage(BaseModel):
    msg: str
    locs: list[Location] = Field(
        default_factory=lambda: [], description='Locations for this message'
    )
    backtrace: str | None = Field(default=None, description='Captured backtrace')


class Error(BaseModel):
    msg: ErrorMessage | None = Field(
        default=None, description='The toplevel error message'
    )
    kind: str = Field(description='A string description of the kind of error')
    stack: list[ErrorMessage] = Field(
        default_factory=lambda: [], description='Context for the error'
    )
    process: str | None = Field(default=None)
